export const portfolioData = [
  {
    id: 1,
    image: '/../src/assets/portfolioImages/website-development1.jpg',
    title: 'Разработка веб-сайта',
    categoryEN: 'Website development',
    categoryRU: 'Разработка веб-сайта',
  },
  {
    id: 2,
    image: '/../src/assets/portfolioImages/website-development2.jpg',
    title: 'Разработка веб-сайта',
    categoryEN: 'Website development',
    categoryRU: 'Разработка веб-сайта',
  },
  {
    id: 3,
    image: '/../src/assets/portfolioImages/website-development3.jpg',
    title: 'Разработка веб-сайта',
    categoryEN: 'Website development',
    categoryRU: 'Разработка веб-сайта',
  },
  {
    id: 4,
    image: '/../src/assets/portfolioImages/website-development4.jpg',
    title: 'Разработка веб-сайта',
    categoryEN: 'Website development',
    categoryRU: 'Разработка веб-сайта',
  },
  {
    id: 5,
    image: '/../src/assets/portfolioImages/bot-development1.jpg',
    title: 'Разработка бота',
    categoryEN: 'Bot development',
    categoryRU: 'Разработка бота',
  },
  {
    id: 6,
    image: '/../src/assets/portfolioImages/bot-development2.jpg',
    title: 'Разработка бота',
    categoryEN: 'Bot development',
    categoryRU: 'Разработка бота',
  },
  {
    id: 7,
    image: '/../src/assets/portfolioImages/bot-development3.jpg',
    title: 'Разработка бота',
    categoryEN: 'Bot development',
    categoryRU: 'Разработка бота',
  },
  {
    id: 8,
    image: '/../src/assets/portfolioImages/bot-development4.jpg',
    title: 'Разработка бота',
    categoryEN: 'Bot development',
    categoryRU: 'Разработка бота',
  },

  {
    id: 9,
    image: '/../src/assets/portfolioImages/SMM1.jpg',
    title: 'SMM',
    categoryEN: 'SMM',
    categoryRU: 'SMM',
  },
  {
    id: 10,
    image: '/../src/assets/portfolioImages/SMM2.jpg',
    title: 'SMM',
    categoryEN: 'SMM',
    categoryRU: 'SMM',
  },
  {
    id: 11,
    image: '/../src/assets/portfolioImages/SMM3jpeg.jpeg',
    title: 'SMM',
    categoryEN: 'SMM',
    categoryRU: 'SMM',
  },
  {
    id: 12,
    image: '/../src/assets/portfolioImages/SMM4.jpg',
    title: 'SMM',
    categoryEN: 'SMM',
    categoryRU: 'SMM',
  },
  {
    id: 13,
    image: '/../src/assets/portfolioImages/SEO1.jpg',
    title: 'SEO',
    categoryEN: 'SEO',
    categoryRU: 'SEO',
  },
  {
    id: 14,
    image: '/../src/assets/portfolioImages/SEO2.jpg',
    title: 'SEO',
    categoryEN: 'SEO',
    categoryRU: 'SEO',
  },
  {
    id: 15,
    image: '/../src/assets/portfolioImages/SEO3.jpg',
    title: 'SEO',
    categoryEN: 'SEO',
    categoryRU: 'SEO',
  },
  {
    id: 16,
    image: '/../src/assets/portfolioImages/SEO4.jpg',
    title: 'SEO',
    categoryEN: 'SEO',
    categoryRU: 'SEO',
  },
  {
    id: 17,
    image: '/../src/assets/portfolioImages/mobile-development1.jpg',
    title: 'Мобильная разработка',
    categoryEN: 'Mobile Development',
    categoryRU: 'Мобильная разработка',
  },
  {
    id: 18,
    image: '/../src/assets/portfolioImages/mobile-development2.jpg',
    title: 'Мобильная разработка',
    categoryEN: 'Mobile Development',
    categoryRU: 'Мобильная разработка',
  },
  {
    id: 19,
    image: '/../src/assets/portfolioImages/mobile-development3.jpg',
    title: 'Мобильная разработка',
    categoryEN: 'Mobile Development',
    categoryRU: 'Мобильная разработка',
  },
  {
    id: 20,
    image: '/../src/assets/portfolioImages/mobile-development4.jpg',
    title: 'Мобильная разработка',
    categoryEN: 'Mobile Development',
    categoryRU: 'Мобильная разработка',
  },
  {
    id: 21,
    image: '/../src/assets/portfolioImages/mobile-development1.jpg',
    title: 'Контекстная реклама',
    categoryEN: 'Contextual advertising',
    categoryRU: 'Контекстная реклама',
  },
  {
    id: 22,
    image: '/../src/assets/portfolioImages/contextual-advertising2.jpg',
    title: 'Контекстная реклама',
    categoryEN: 'Contextual advertising',
    categoryRU: 'Контекстная реклама',
  },
  {
    id: 23,
    image: '/../src/assets/portfolioImages/mobile-development3.jpg',
    title: 'Контекстная реклама',
    categoryEN: 'Contextual advertising',
    categoryRU: 'Контекстная реклама',
  },
  {
    id: 24,
    image: '/../src/assets/portfolioImages/mobile-development4.jpg',
    title: 'Контекстная реклама',
    categoryEN: 'Contextual advertising',
    categoryRU: 'Контекстная реклама',
  },
];

export const portfolioNavData = [
  {
    name: 'Разработка веб-сайта',
  },
  {
    name: 'Разработка бота',
  },
  {
    name: 'SMM',
  },
  {
    name: 'SEO',
  },
  {
    name: 'Мобильная разработка',
  },
  {
    name: 'Контекстная реклама',
  },
];
